# config/attack_config.yaml


common:
  image_size : &img_size 512  # 定义锚点，后续可通过 *img_size 引用



# ADV_ATTACK的默认参数（新增）
attak_params:
  prompt: "covered with realistic asphalt road texture, irregular dark gray and black patches, worn urban street surface, fine gravel and subtle crack details, matte road texture, high detail, 8k resolution"
  a_prompt: ""
  n_prompt: ". blurry, low resolution, ugly, deformed, noisy texture, pixelated, unrealistic, bad detail, distorted pattern, edge mismatch, pattern fragmentation, over-saturated colors, glossy surface, cartoonish, 3d render artifacts, extra edges, missing edges"
  ddim_steps: 30
  guess_mode: false
  strength: 0.8 # 默认 1.0, 0.7 纹理更丰富
  scale: 9   # 默认9
  scale_optim: 9
  seed: 42
  eta: 0.0
  save_memory: true


  amp_status: true 




  


