# config/attack_config.yaml


image_size : 512 

render_size:
  width: 512
  height: 512
device: "cuda"  
# optim params
optim_epochs: 2
lr: 0.05     #0.05   
lr_step: 10 # 10  ,按迭代次数算
lr_decay: 0.8


 
# amp_status: true 
use_amp : false
use_bf16 : true 


adv_loss_type: 1   

# 0:表示与gt的交叉熵最大；
# 1:表示最小化当前预测类别的置信度；
# 2：带有参考类型，最大化误导类别的置信度，最小化当前类别的置信度
optim_object_type: 0
# 0 表示优化latent
# 1 表示直接优化RGB图片
# 2 表示经过VAE，优化RGB图像

target_class: 2 # 目标类别，参考COCO类别对应,参考类别




TV_loss_weight: 0.1
conext_loss_weight: 10 ## 默认 1：1000 默认2：2000
perceptual_loss_weight: 0.01 ## 默认1： 1000 默认2：1000
class_loss_weight : 1  # 1  
HUV_loss_weight : 5

texture_path : /root/autodl-fs/MM3Dadv_exp/attack/baseline_cmp/yolov3/texture/texture_final.pt
experiment_path: /root/autodl-fs/MM3Dadv_exp/val/attack_val_20260502/baseline

iou_threshold_val: 0.5
conf_threshold_val: 0.5




dataloader:
  target: dataload.DualAttentionAttack_loader.MyDataset
  params:
    data_dir: /root/autodl-fs/MM3DAdv_data/baseline_data/phy_attack/test
    img_size: 512
    mask_dir: /root/autodl-fs/MM3DAdv_data/baseline_data/masks


batch_size: 1
num_workers: 4



mesh_model_path: "/root/autodl-fs/MM3DAdv_data/3Dmodel/audi/audi_et_te_origin.obj"

render_face_size : 1  # 面个数
target_material_dict :
  - "MI_CarExterior_Etron"


# mesh_model_path: "/root/autodl-fs/MM3DAdv_data/3Dmodel/mazda/mazda.obj"
# mesh_model_path: "/root/autodl-fs/MM3DAdv_data/3Dmodel/audi/audi_et_te_origin.obj"

# render_face_size : 3  # 面个数
# target_material_dict :
#   - "t1"
#   - "t2"
#   - "t3"
#   # - "body"
#   # - "MAT_Tire_Hub.001"