# config/attack_config.yaml


image_size : 512 

render_size:
  width: 1280
  height: 720
device: "cuda"  
# optim params
optim_epochs: 10
lr: 0.001     #0.05   # 默认0.5
lr_step: 40 # 10
lr_decay: 0.8



# amp_status: true 
use_amp : false
use_bf16 : true 


adv_loss_type: 1   

# 0:表示与gt的交叉熵最大；
# 1:表示最小化当前预测类别的置信度；
# 2：带有参考类型，最大化误导类别的置信度，最小化当前类别的置信度
optim_object_type: 0
# 0 表示优化latent
# 1 表示直接优化RGB图片
# 2 表示经过VAE，优化RGB图像

target_class: 2 # 目标类别，参考COCO类别对应,参考类别




TV_loss_weight: 0.1
conext_loss_weight: 10 ## 默认 1：1000 默认2：2000
perceptual_loss_weight: 0.01 ## 默认1： 1000 默认2：1000
class_loss_weight : 1  # 1  
HUV_loss_weight : 5

experiment_path: "exp/260112_optim_test/" 
# 较近距离，4m
train_root_dir : "/root/autodl-fs/MM3DAdv_data/env_data/carla_sample_data20260316_real_4m/vehicle_tesla_model3/location_000"
val_root_dir : "/root/autodl-fs/MM3DAdv_data/env_data/carla_sample_data20260316_real_4m/vehicle_tesla_model3/location_000_random"

batch_size: 1
num_workers: 4

mesh_model_path: "/root/autodl-fs/MM3DAdv_data/3Dmodel/mazda/mazda_part.obj"

render_face_size : 2  # 面个数
target_material_dict :
  - "t1"
  - "t2"
  # - "body"
  # - "MAT_Tire_Hub.001"